#!/usr/bin/python3
# -*- coding: utf-8 -*-
import argparse
import configparser
import glob
import os
import re
import subprocess
import syslog

import log

DEFAULT_CONFIG = "/home/pi/irigatie/irigatie.conf"
DEFAULT_SYSTEMD_DIR = "/etc/systemd/system"
SERVICE_TEMPLATE_NAME = "irigatie-program@.service"
TIMER_PREFIX = "irigatie-program-"
TIMER_SUFFIX = ".timer"
GENERATED_MARKER = "# Generated by generate_systemd_schedules.py"
DOW_NAMES = {
    0: "Sun",
    1: "Mon",
    2: "Tue",
    3: "Wed",
    4: "Thu",
    5: "Fri",
    6: "Sat",
    7: "Sun",
}


class ScheduleError(Exception):
    pass


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate systemd timers for irrigation schedules")
    parser.add_argument(
        "-c", "--config", default=DEFAULT_CONFIG,
        help="path to irigatie.conf")
    parser.add_argument(
        "--systemd-dir", default=DEFAULT_SYSTEMD_DIR,
        help="directory for generated systemd units")
    parser.add_argument(
        "--dry-run", action="store_true",
        help="print generated units without writing or running systemctl")
    return parser.parse_args()


def read_config(path):
    config = configparser.ConfigParser()
    if not config.read(path):
        raise ScheduleError("Could not read config file: %s" % path)
    return config


def connect_db(config):
    import pymysql

    return pymysql.connect(
        host=config.get("SQL", "DB_SERVER", fallback="127.0.0.1"),
        port=config.getint("SQL", "DB_PORT", fallback=3306),
        user=config.get("SQL", "DB_USER"),
        password=config.get("SQL", "DB_PASS"),
        db=config.get("SQL", "DB_NAME"),
        autocommit=True,
        cursorclass=pymysql.cursors.DictCursor,
    )


def parse_field(value, minimum, maximum, field_name, allow_step=False):
    value = str(value).strip()
    if value == "*":
        return None

    values = set()
    for part in value.split(","):
        part = part.strip()
        if not part:
            raise ScheduleError("Empty value in %s field: %r" % (field_name, value))

        match = re.match(r"^\*/(\d+)$", part)
        if match:
            if not allow_step:
                raise ScheduleError("Step syntax is not supported in %s field: %r" % (field_name, value))
            step = int(match.group(1))
            if step <= 0:
                raise ScheduleError("Invalid step in %s field: %r" % (field_name, value))
            for number in range(minimum, maximum + 1, step):
                values.add(number)
            continue

        if re.match(r"^\d+$", part):
            number = int(part)
            validate_number(number, minimum, maximum, field_name, value)
            values.add(number)
            continue

        match = re.match(r"^(\d+)-(\d+)$", part)
        if match:
            start = int(match.group(1))
            end = int(match.group(2))
            validate_number(start, minimum, maximum, field_name, value)
            validate_number(end, minimum, maximum, field_name, value)
            if start > end:
                raise ScheduleError("Descending range in %s field: %r" % (field_name, value))
            for number in range(start, end + 1):
                values.add(number)
            continue

        raise ScheduleError("Unsupported %s field value: %r" % (field_name, value))

    return sorted(values)


def validate_number(number, minimum, maximum, field_name, original):
    if number < minimum or number > maximum:
        raise ScheduleError(
            "%s field value %s outside %s-%s in %r" %
            (field_name, number, minimum, maximum, original)
        )


def expand_or_all(values, minimum, maximum):
    if values is None:
        return list(range(minimum, maximum + 1))
    return values


def calendar_lines(row):
    minutes = parse_field(row["m"], 0, 59, "minute")
    hours = parse_field(row["h"], 0, 23, "hour")
    month_days = parse_field(row["dom"], 1, 31, "day-of-month", allow_step=True)
    months = parse_field(row["mon"], 1, 12, "month")
    week_days = parse_field(row["dow"], 0, 7, "day-of-week", allow_step=True)

    if month_days is not None and week_days is not None:
        raise ScheduleError(
            "programari.id=%s restricts both dom and dow; this is intentionally unsupported" %
            row["id"]
        )

    line_values = []
    for month in expand_or_all(months, 1, 12):
        for day in expand_or_all(month_days, 1, 31):
            for hour in expand_or_all(hours, 0, 23):
                for minute in expand_or_all(minutes, 0, 59):
                    date_part = "*-%02d-%s" % (
                        month, "*" if month_days is None else "%02d" % day
                    )
                    time_part = "%02d:%02d:00" % (hour, minute)
                    if week_days is None:
                        line_values.append("%s %s" % (date_part, time_part))
                    else:
                        for week_day in week_days:
                            line_values.append("%s %s %s" % (
                                DOW_NAMES[week_day], date_part, time_part
                            ))

    return sorted(set(line_values))


def service_template():
    return """%s
[Unit]
Description=Irigatie scheduled program %%i
After=irigatie.service
Requires=irigatie.service

[Service]
Type=oneshot
WorkingDirectory=/home/pi/irigatie
ExecStart=/usr/bin/python3 /home/pi/irigatie/client.py -c START -p %%i
""" % GENERATED_MARKER


def timer_unit(row):
    lines = [
        GENERATED_MARKER,
        "[Unit]",
        "Description=Irigatie schedule %s" % row["id"],
        "",
        "[Timer]",
        "Unit=irigatie-program@%s.service" % row["id"],
        "Persistent=false",
    ]
    for calendar_line in calendar_lines(row):
        lines.append("OnCalendar=%s" % calendar_line)
    lines.extend([
        "",
        "[Install]",
        "WantedBy=timers.target",
        "",
    ])
    return "\n".join(lines)


def timer_name(program_id):
    return "%s%s%s" % (TIMER_PREFIX, program_id, TIMER_SUFFIX)


def write_file(path, content, dry_run):
    if dry_run:
        print("### %s" % path)
        print(content)
        return

    tmp_path = path + ".tmp"
    with open(tmp_path, "w") as handle:
        handle.write(content)
    os.replace(tmp_path, path)


def is_generated(path):
    try:
        with open(path) as handle:
            return handle.readline().strip() == GENERATED_MARKER
    except IOError:
        return False


def run_systemctl(args, dry_run):
    command = ["systemctl"] + args
    if dry_run:
        print("DRY-RUN:", " ".join(command))
        return
    subprocess.check_call(command)


def remove_stale_timers(systemd_dir, active_names, dry_run):
    pattern = os.path.join(systemd_dir, TIMER_PREFIX + "*" + TIMER_SUFFIX)
    for path in glob.glob(pattern):
        name = os.path.basename(path)
        if name in active_names:
            continue
        if not is_generated(path):
            raise ScheduleError("Refusing to remove non-generated timer: %s" % path)
        run_systemctl(["stop", name], dry_run)
        run_systemctl(["disable", name], dry_run)
        if dry_run:
            print("DRY-RUN: remove %s" % path)
        else:
            os.remove(path)


def load_schedules(conn):
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT id, m, h, dom, mon, dow "
            "FROM programari WHERE activ != 0 ORDER BY id;"
        )
        return cursor.fetchall()


def main():
    args = parse_args()
    config = read_config(args.config)
    conn = connect_db(config)
    try:
        schedules = load_schedules(conn)
    finally:
        conn.close()

    if not args.dry_run and not os.path.isdir(args.systemd_dir):
        raise ScheduleError("systemd directory does not exist: %s" % args.systemd_dir)

    active_timer_names = set()
    service_path = os.path.join(args.systemd_dir, SERVICE_TEMPLATE_NAME)
    if os.path.exists(service_path) and not is_generated(service_path):
        raise ScheduleError("Refusing to overwrite non-generated service: %s" % service_path)
    write_file(service_path, service_template(), args.dry_run)

    for row in schedules:
        name = timer_name(row["id"])
        active_timer_names.add(name)
        timer_path = os.path.join(args.systemd_dir, name)
        if os.path.exists(timer_path) and not is_generated(timer_path):
            raise ScheduleError("Refusing to overwrite non-generated timer: %s" % timer_path)
        write_file(timer_path, timer_unit(row), args.dry_run)

    remove_stale_timers(args.systemd_dir, active_timer_names, args.dry_run)
    run_systemctl(["daemon-reload"], args.dry_run)
    for name in sorted(active_timer_names):
        run_systemctl(["enable", name], args.dry_run)
        run_systemctl(["start", name], args.dry_run)

    log.info('schedule_generator', 'generated irrigation timers',
             count=len(active_timer_names))


if __name__ == "__main__":
    syslog.openlog('irigatie-schedule-generator')
    try:
        main()
    except ScheduleError as exc:
        log.err('schedule_generator', 'failed', error=str(exc))
        raise SystemExit(1)
